### ISSUE TITLE
Add support for venue field

### ISSUE THREAD

**Issue by zhm** [JasonSanford/geobooze-slack#1]
Can it hit the 4sq API to find matches somehow? Would be cool if it could fuzzy match the given venue against 4sq venues in the area.

Maybe:

- Extract lat/long from record
- Pull 4sq venues around that area
- Add all the venues to a temp index, maybe https://github.com/olivernn/lunr.js/
- Look for the user given venue in the index
- Link the venue in the message text

**Comment by JasonSanford** [comment]
This was fixed a while back.
